services:
  node0:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['0', '3', '2', '8', '1']
  node1:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['1', '5', '4', '0']
  node2:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['2', '0']
  node3:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['3', '0']
  node4:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['4', '1']
  node5:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['5', '9', '6', '1']
  node6:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['6', '7', '5']
  node7:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['7', '6']
  node8:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['8', '0']
  node9:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['9', '5']
